### ISSUE TITLE
Idle server using CPU resources

### ISSUE THREAD

**Issue by DeathByDenim** [opensoldat/opensoldat#126]
Currently, opensoldatserver uses CPU resources even when there are no human players. It's not too bad (<10%), but ideally an idle server should use almost nothing. It all adds up if you run multiple game servers on a single server which is what I do.

This could be fixed by inserting the following at [server/Serverloop:40](https://github.com/opensoldat/opensoldat/blob/ef4aa67faccf6550cfddadc165b7360c6edb3d21/server/ServerLoop.pas#L40) after the `AdminServer.ProcessCommands();` thing:
```
  if (PlayersNum - BotsNum) <= 0 then
  begin
    Sleep(100);
    Exit;
  end;
```

I looked through the rest of the `AppOnIdle` procedure, but I didn't see anything where this would cause issues. I played a few test games and it does work. CPU usage is nearly 0% when there are only bots. Spectating bots playing works as well.

The round time limit is paused too. That is, if there were X seconds left on the map and the last human players quits, then when a human player joins again after a few minutes, the round count down will continue from those X seconds.

The only side effect that I could see is that a player may be waiting for up to 100ms before being allowed to join the server due to the `Sleep(100)`. That's hardly noticeable tough.

Thoughts?

**Comment by BranDougherty** [comment]
- Lobby registration is not working right now but the current design is to send a registration HTTP request every minute, based on tick counter. It can probably just be pulled out of the loop and ran based on `GetTickCount64` calls.
- Scripts would not be able to run any code for the whole time the server is idle, we should probably add an `OnIdle` event.
- Most server owners will want this, so it should be default behavior. But maybe some people will get creative with scripts and want to keep the server running, it should be configurable.
- Maybe the Steam `RunManualCallbacks` code needs to be pulled out as well? Would need to look into that.

In general supporting this feature in this way means:

- Splitting out code which interacts with external systems in a time sensitive fashion
- Being more thoughtful about how we measure time (seconds vs ticks).

So there is a decent amount to consider in supporting this feature, and implementing it would require some care around the way time is handled in the game. But right now those actually sound like good structural changes to make anyways, and of course it would be great for server owners. So +1 from me.

**Comment by DeathByDenim** [comment]
* Oh, I see. The lobby update is in `UpdateFrame`. Right, so it seems to be only called when `BulletTimeTimer < 1` which I guess is almost always true expect for a very short time after a Sprite dies? Like 30 ticks as far as I can tell. I'm guessing that's not too important for the lobby update and doing the Lobby update can be pulled out like you said.
* True, scripts will pause as well which I figured was a good thing.
* I definitely see your point though! Like you say, some people will get creative. Adding a new CVar like `sv_pause_on_idle` or something could be a new option to keep the server running without players. Would you still need that new `OnIdle` event in that case?
* Yeah, I wasn't sure about Steam. It doesn't look like it needs to be called every tick at first glance except maybe `SteamAPI_ManualDispatch_RunFrame`, though from what little I could find about that from a quick search, it seems recommended run call this [>10Hz to avoid delays with Steam notifications](https://partner.steamgames.com/doc/api/steam_gameserver#SteamGameServer_RunCallbacks). Then again, how many notifications can there be for an idle server?

Anyway, I'll tinker some with that this weekend and see what else I can find.
