### ISSUE TITLE
hum.wav - close explosion hum in ears effect - lack of transition from 0->100% sound volume

### ISSUE THREAD

**Issue by Dankage102** [opensoldat/opensoldat#129]
Compared both 1.7 and 1.8 versions and sounds like 1.8 is missing the transition.

**Comment by BranDougherty** [comment]
We probably lost it going from FMOD to OpenAL (like how we lost the ability to play the music files). I tried putting Audacity's "Fade In" on the first second of the effect, and it sounded pretty good to me so I'm tempted to just do that. Alternatively, we could fade in based on `GrenadeEffectTimer`'s value, or maybe do something fancier? No clue what that would be, not an audio guy.

**Comment by Dankage102** [comment]
It's not the hum.wav sound effect that needs to be changed but master sound of the game. Now, during the effect, all sounds are set to 0% for the whole time of the effect(try shooting during the effect and you will see), ideally it would start to slowly bring back all old volume values let's say after half time of the effect.

**Comment by BranDougherty** [comment]
Feel free to open a new issue/PR if you want to tweak the effect or have some opinions on it.
