### ISSUE TITLE
/say admin command doesn't work anymore

### ISSUE THREAD

**Issue by Dankage102** [opensoldat/opensoldat#132]
It was used by TCP clients to send messages to console, also by in-game admins to inform players about something important or even checking if they are already logged in as admin. Now all players seem to have some kind of /say command which works the same as typing on "t", dunno really what's the point of that.

**Comment by BranDougherty** [comment]
Client side `/say` command is used for taunts, see default bindings.cfg. Also thanks for testing and opening issues.
