### ISSUE TITLE
demos recorded in Mac client are corrupt

### ISSUE THREAD

**Issue by marktani** [opensoldat/opensoldat#14]
If you record a demo on the native Mac client, it cannot be viewed on any client.
Opening the demo simply crashes the client.

This is a known issue but would like it to be fixed, or at least understand the issue so I could take a stab at it myself.

Edit: I can upload a sample demo tonight.

**Comment by marktani** [comment]
[Ash.sdm.zip](https://github.com/Soldat/soldat/files/4705405/Ash.sdm.zip)

This is a demo recorded in the Mac client exhibiting above behavior.

**Comment by furai** [comment]
Thanks for reporting. Quick question. Did you compile yourself the latest code or are you using some older build from helloer?

**Comment by marktani** [comment]
I am using some older build from helloer, I downloaded it at 2020-04-30. It says `1.7.1.3` in game. 

More information, running `"/Applications/soldatlauncher.app/Contents/Resources/Soldat Client.app/Contents/MacOS/soldat" -join Ash 0 log_level 2` I can actually run the demo successfully, however I believe that you cannot open it on Windows.

**Comment by Shoozza** [comment]
Could you retry if this issue is still present in the open source version build from this repository? We don't have access to the proprietary build code neither do we know how old it is.
Thanks.

**Comment by BranDougherty** [comment]
Feel free to reopen if this is still affecting you with the current version (to be honest I think there is a lot of work yet to do with the demo system).
