### ISSUE TITLE
Tag the initial commit

### ISSUE THREAD

**Issue by Thann** [opensoldat/opensoldat#16]
I makes sense to me to tag the initial commit at `v1.8.0` so packagers have a canonical version to work with. =]

**Comment by furai** [comment]
I agree but I'm not sure that `v1.8.0` should be the initial tag. The 1.8 version is the aim for us. To make it. The repo in current state is far from 1.8. So we probably should call it differently. I don't know right now what. Maybe `v1.8.0-alpha` Maybe some smaller number. Anything that actually fits cause initial commit for sure isn't 1.8.

Do you guys have any ideas?

**Comment by Thann** [comment]
I think `v1.8.0-alpha` is fine.

**Comment by Shoozza** [comment]
I'd say we should mostly follow https://semver.org/.
With the exception that the first number 1 will stick and the Patch number can be dropped if 0:
`1.X.Y.Z-P+A` (1.Major.Minor.Patch-Prerelease+Build)

Maybe we can also drop the v at the beggining (or is it a convention to use it in linux packages?)
So `1.8.0-alpha+initial`
skipping the Patch number when not necessary
and using the Build meta information `initial` so we know it is the initial release of the source code - maybe `1.8.0-alpha+initial-floss` to be 100% clear.

What do you think? Also are there any potential issues with that suggestion for packaging?

**Comment by furai** [comment]
So what is the decision? `1.8.0-alpha+initial` ? I don't think `floss` part is required, it's on GitHub, it's open source, it has a license. What else would it be than FOSS/FLOSS.

**Comment by Shoozza** [comment]
initial tag: `1.8.0-alpha+initial` created
