### ISSUE TITLE
Launcher built with GitHub Actions in this repo trying to load preload.js from nonexistent path.

### ISSUE THREAD

**Issue by BranDougherty** [opensoldat/opensoldat#167]
Running the Launcher, when built with the GitHub Actions from this repo, results in the following errors:
`Unable to load preload script: /home/runner/work/opensoldat/opensoldat/launcher/.webpack/renderer/main_window/preload.js
(anonymous) @ VM126 renderer_init:73`
![shot_10-2022-29_16-36-12](https://user-images.githubusercontent.com/19610490/198853274-51a9f74a-91b1-48ed-b705-2b67d5e8fc62.png)

Not sure of the cause, but it could have something to do with recent dependency updates, or Node.js version updates.

**Comment by rzaba0** [comment]
Seems related to https://github.com/electron/forge/issues/3020
Production builds made locally (`npm run make`) don't work either; running the executable leads to the same error message mentioned in the linked issue

**Comment by rzaba0** [comment]
Should work now. I updated electron-forge to the latest version - https://github.com/opensoldat/launcher/commit/59b6521673596f6a9440e8e932d97faa92386d3a

**Comment by BranDougherty** [comment]
I just reran the action with no changes and it worked, thanks!
