### ISSUE TITLE
Last mesa update (mesa 20.1.1-1) Broke Soldat 

### ISSUE THREAD

**Issue by tinoolski** [opensoldat/opensoldat#18]
I've to downgrade to mesa-20.0.7-3 to keep using the linux native client. Can't see any log (I tried to use log level 1 / 2) but didn't show anything. It's seems a rendering problem because it's show all textures red.

**Comment by Shoozza** [comment]
Is there a report for this breakage on the mesa project?

**Comment by BranDougherty** [comment]
This can be closed. I probably should mention my patch for this landed upstream and is in 20.2.3 and 20.3.0. If someone experiences this problem just run git pull or update your packages.

**Comment by Shoozza** [comment]
Thanks :)
