### ISSUE TITLE
Incorrect instructions about pre-built libraries?

### ISSUE THREAD

**Issue by Wuzzy2** [opensoldat/opensoldat#33]
The install instructions say:

> Download [pre-built libraries](https://github.com/Soldat/prebuilt-libs/archive/master.zip) and copy libraries from `win64_dlls` to `client/build` and `server/build`

What if I'm on GNU/Linux? Do I also need the pre-built libraries then? And if yes, I'm guessing it won't be `win64_dlls`. ;-)

It seems the README might be incorrect/misleading here. Can you please clarify this step?

**Comment by Wuzzy2** [comment]
OK, I now know the answer to this question.
The prebuilt libraries are NOT required to build this game under GNU/Linux.
I managed to build it with:

- FPC 3.0.4 (Arch Linux package)
- libGameNetworkSocket (built myself, that one specific commit the game expects)
- libstb (built myself)
- PhysFS 3.0.2 (Arch Linux package)

So, the instructions are incorrect if you're on a GNU/Linux system, so please fix this. :-)

See also: https://github.com/Soldat/soldat/issues/7#issuecomment-658373104

**Comment by Mailaender** [comment]
What is that one commit the game expects? I tried [GameNetworkingSockets v1.2.0](https://github.com/ValveSoftware/GameNetworkingSockets/releases/tag/v1.2.0) and always get

```
[    8s] /usr/bin/ld: ./build/linux/GameNetworkingSockets.o: in function `INIT':
[    8s] /home/abuild/rpmbuild/BUILD/soldat-1.8.0+git.20200525/server//../shared/libs/GameNetworkingSockets/GameNetworkingSockets.pas:1631: undefined reference to `SteamAPI_SteamNetworkingSockets_v008'
[    8s] /usr/bin/ld: ./build/linux/GameNetworkingSockets.o: in function `RUNCONNECTIONSTATUSCHANGEDCALLBACKS':
[    8s] /home/abuild/rpmbuild/BUILD/soldat-1.8.0+git.20200525/server//../shared/libs/GameNetworkingSockets/GameNetworkingSockets.pas:1749: undefined reference to `SteamAPI_ISteamNetworkingSockets_RunConnectionStatusChangedCallbacks'
[    9s] /home/abuild/rpmbuild/BUILD/soldat-1.8.0+git.20200525/server/soldatserver.lpr(49,1) Error: (9013) Error while linking
[    9s] /home/abuild/rpmbuild/BUILD/soldat-1.8.0+git.20200525/server/soldatserver.lpr(49,1) Fatal: (10026) There were 1 errors compiling module, stopping
```

**Comment by helloer** [comment]
Build instructions have been updated, [pre-built libraries](https://github.com/Soldat/prebuilt-libs/archive/master.zip) from the repo are not used anymore.

**Comment by Mailaender** [comment]
@mnhauke
