### ISSUE TITLE
Esc key does not work in loading/error screen

### ISSUE THREAD

**Issue by Wuzzy2** [opensoldat/opensoldat#38]
If I start the Soldat client and I have either the loading screen or the network error screen (ping timeout/could not connect to server), the window says I can press Esc to quit. However, this does not work. I have to kill the process to get out.

System information:

    OS: Linux 5.7.8 (Arch Linux)
    Pascal: FPC 3.0.4
    libGameNetworkingSockets: built myself, commit 8f60b0e (as recommended here: Soldat/prebuilt-libs#1 (comment))
    libstb: built myself in Soldat repository
    libphysfs: 3.0.2
    make: GNU Make 4.3
    Soldat: commit 078795a

**Comment by zenyd** [comment]
Are you only launching the client, without server, or how do you get to this screen?

**Comment by Wuzzy2** [comment]
This happens when I either did not start the server at all or I try to connect to an address for which there is no server. This was intentional, in order to test for bugs … :P

The bug is not that the error message appears (in fact, the error message is exactly right), but the bug is that the Esc key does not work in these screens. The window should close when I hit Esc, but it doesn't.
