### ISSUE TITLE
Error writing PID file (linux docker)

### ISSUE THREAD

**Issue by robinchm** [opensoldat/opensoldat#50]
I am trying to build a docker image for soldat server using the latest develop commit. The reason for that is because installing fpc 3.0.4 is a very difficult task on my ubuntu 20.10 box, when the package manager provides only 3.2.0. Manually installing 3.0.4 and I get missing library prompt during the build process.

The Dockerfile currently looks like (WIP):

```dockerfile
FROM ubuntu:18.04

WORKDIR /workspace

COPY GameNetworkingSockets-1.2.0.tar.gz ./
COPY soldat/ soldat/

RUN apt-get update \
  && apt-get install -y git cmake ninja-build golang libssl-dev libprotobuf-dev protobuf-compiler fpc libsdl2-2.0-0 libsdl2-dev libopenal-dev libphysfs-dev libphysfs1

RUN tar xf GameNetworkingSockets-1.2.0.tar.gz \
  && cd GameNetworkingSockets-1.2.0 \
  && mkdir build \
  && cd build \
  && cmake -G Ninja .. \
  && ninja \
  && mv bin/libGameNetworkingSockets.so /usr/lib/

RUN cd ../../soldat/server && make
RUN adduser --disabled-password --gecos "" soldat && su soldat

ENTRYPOINT ["sleep", "3600"]
```
I am still testing the build process so at the moment I exec into the container to perform tasks.
I managed to build the server but when it gave the following error when executed:
```

             -= Soldat Dedicated Server 1.8.0 - 2.9.0 (build ) =-

----------------------------------------------------------------
         Soldat Dedicated Server initializing...
----------------------------------------------------------------

   Need help running your server?
   Discord: https://discord.gg/soldat

   ---> https://forums.soldat.pl/

   Additional parameters:
   ./soldatserver -net_port PORT -sv_maxplayers MAXPLAYERS -sv_password PASSWORD
   Example: ./soldatserver -net_port 23073 -sv_maxplayers 16 -sv_password "my pass"


 Compiled with FreePascal 3.0.4

Could not load base game archive (soldat.smod).
Error writing PID file
----------------------------------------------------------------
Shutting down server...
An unhandled exception occurred at $000000000041B9F7:
EAccessViolation: Access violation
  $000000000041B9F7
  $0000000000418A71
```

It looks like the server wants to write a pid file somewhere but cannot do so. A few things:
* I need to sudo to user because the server refuses to run as root - maybe this limitation can be removed?
* When run as a normal user maybe it's trying to write a pid file somewhere but failed due to missing privilege - but I don't know where it's attempting to write. Copying the `soldatserver_x64` to the user's home where it can write also failed with the same error message.

Any hint on how to resolve the error?

**Comment by helloer** [comment]
> The reason for that is because installing fpc 3.0.4 is a very difficult task on my ubuntu 20.10 box, when the package manager provides only 3.2.0.

FPC 3.2.0 should work just fine.
> I need to sudo to user because the server refuses to run as root - maybe this limitation can be removed?

I agree, it should be removed as it doesn't provide any _real_ security benefits. Maybe it could be your first PR?:)

> When run as a normal user maybe it's trying to write a pid file somewhere but failed due to missing privilege - but I don't know where it's attempting to write. Copying the soldatserver_x64 to the user's home where it can write also failed with the same error message.

You need soldat.smod next to soldatserver_x64 in order to run it. `Error writing PID file` shows up because it cannot write to `logs/soldatserver.pid` since `logs` directory is not yet here, it will be created after .smod is successfully loaded

**Comment by robinchm** [comment]
> FPC 3.2.0 should work just fine.

As reported in this issue: #34, compiling with fpc-3.2.0 will cause the server to fail at runtime.

My first attempt was indeed to compile with fpc-3.2.0. The compilation itself succeeded, but running the server gave:
`EAccessViolation: Access violation` without other error message.

> I agree, it should be removed as it doesn't provide any real security benefits. Maybe it could be your first PR?:)

PR filed: #53. I am not fluent with pascal though.

> You need soldat.smod next to soldatserver_x64 in order to run it. Error writing PID file shows up because it cannot write to logs/soldatserver.pid since logs directory is not yet here, it will be created after .smod is successfully loaded

I'll try with the `soldat.mod` found on the wiki, thanks!

**Comment by sternenseemann** [comment]
> I need to sudo to user because the server refuses to run as root - maybe this limitation can be removed?

Why? There is actually no reason why this would be necessary. There must be a way to have normal users in docker as well.

**Comment by robinchm** [comment]
> > I need to sudo to user because the server refuses to run as root - maybe this limitation can be removed?
> 
> Why? There is actually no reason why this would be necessary. There must be a way to have normal users in docker as well.

Yes you can see in my docker file I created a user to run the server. Just feel it's not necessary to guard against running as root in the code (I don't see many software do that). In fact the check is skipped for windows platform. I am ok with both ways.

**Comment by jrgp** [comment]
@robinchm there are a few reasons why it's a good idea to make the Soldat server not run as root within the container:

1. It's possible some buggy scripts will allow users to run arbitrary CLI programs and get a root shell
2. It's possible there are bugs within the soldat server we aren't aware of yet, that will allow malicious people to get a root shell

And most of all: if you get root inside a docker container, it becomes more possible for a malicious agent to escape from the container into the host system. Not to mention abuse anything else running inside that container. 

My two cents: just have an optional CLI argument to override the root check like most software does. 

Also, the windows process sandboxing/user model is very different than on Unix/Linux so you can't directly compare them.

**Comment by Shoozza** [comment]
One a compromise would be to add a commandline argument for people who want to run it as root despite our recommendation to not do so.

The command could be `--root` and we could mention it in the error you get if you run it as root.
