### ISSUE TITLE
Why Pascal?

### ISSUE THREAD

**Issue by Martinsos** [opensoldat/opensoldat#54]
Cool project! I remember playing a shooter named Soldat long time ago, it was this one: https://store.steampowered.com/app/638490/Soldat/ .

Just wondering, why Pascal? I used it long time ago, it was my first language that I learned, but I thought there are better alternatives today? Maybe it is for "artistic" reasons :D?

**Comment by rafal-zelek** [comment]
Well, soldat was released in 2002 and nobody just have time to rewrite that, especially if it works.

**Comment by Martinsos** [comment]
Oh my this is that same Soldat!? Ha, I thought this was a similar game with similar name, not that it is the same game!! I need to read README more carefully next time, I see now it is all explained there. Cooool, this brings memories from the childhood :D!
