### ISSUE TITLE
Allow linking against system GameNetworkingSockets

### ISSUE THREAD

**Issue by sternenseemann** [opensoldat/opensoldat#73]
Currently the only way to link against GameNetworkingSockets is by building it as an external project. This requires checking out a git repository while building which isn't desireable in a packaging context. Ideally we have one GameNetworkingSockets packgae and one soldat package.

Would be nice if there'd be at least a cmake flag to switch between ordinary dependency and external project.

**Comment by BranDougherty** [comment]
When we're building GNS ourselves we should be downloading the release tarball instead of cloning anyways. And yeah some `option(BUILD_GNS "Build GameNetworkingSockets" True)`, where we link to system GNS if its false, would make sense.
