### ISSUE TITLE
soldatserver: Compatibility with Bionic C library.

### ISSUE THREAD

**Issue by Krush206** [opensoldat/opensoldat#75]
[Bionic](https://android.googlesource.com/platform/bionic/)  is a lightweight C library implementation for the Linux kernel, developed by Google, for use within the Android operating system.

It'd be nice if the server app could be built against Bionic. The main reason to consider this is due the low hardware usage Bionic makes use of, which would translate in efficient, faster server runtime.

**Comment by BranDougherty** [comment]
This doesn't seem like an efficient use of time. Of course anyone is free to implement it if they wish, but soldatserver performance is not on my priority list right now, and I seriously doubt investing into Linux C runtime performance is going to be an effective way to improve that anyways.

**Comment by sternenseemann** [comment]
I also don't think it should be impossible atm, just compiling soldat with bionic as your `libc` _should_ work, unless it relies on some non-POSIX behavior or bionic deviates from POSIX. In any case having concrete build failures here would help gauge how much work it'd be.

**Comment by Krush206** [comment]
I can speak from own experience that Bionic does make things faster. A low-cost laptop of mine can run and multitask Android apps (with Android-x86) without hassle, unlike GNU/Linux. Even game emulators did better under Android.

I hex-edited the soldatserver executable to use Bionic's ELF interpreter (`/system/bin/linker`), but it throws up a unreferenced symbol error:
`CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__cxa_finalize" referenced by "libdl.so.2"`

However, `strings` show me otherwise:
`$ strings /system/lib/libdl.so.2 | grep -F __cxa_finalize`
`__cxa_finalize`
`$ strings /system/lib/libc.so.6 | grep -F __cxa_finalize`
`__cxa_finalize`
`$ strings /system/lib/libpthread.so.0 | grep -F __cxa_finalize`
`__cxa_finalize`
