### ISSUE TITLE
Undefined reference to some gns functions

### ISSUE THREAD

**Issue by ydnatag** [opensoldat/opensoldat#78]
Trying to build soldat from sources, I'm getting the following error:

```
Linking /tmp/soldat/build/bin/soldat
/usr/bin/ld: CMakeFiles/soldat.dir/GameNetworkingSockets.o: in function `GETQUICKCONNECTIONSTATUS':
/tmp/soldat/build/client//../../shared/libs/GameNetworkingSockets/GameNetworkingSockets.pas:1995: undefined reference to `SteamAPI_ISteamNetworkingSockets_GetQuickConnectionStatus'
/usr/bin/ld: CMakeFiles/soldat.dir/GameNetworkingSockets.o: in function `GETFIRSTCONFIGVALUE':
/tmp/soldat/build/client//../../shared/libs/GameNetworkingSockets/GameNetworkingSockets.pas:2124: undefined reference to `SteamAPI_ISteamNetworkingUtils_GetFirstConfigValue'
```

Regards

**Comment by BranDougherty** [comment]
We build against GNS v1.3.0, looks like the connection status and config interfaces changed. When v1.4 is released we'll update, until then build again v1.3.0.

**Comment by ydnatag** [comment]
How can I force GNS version during compilation? (I'm having this issue trying to compile from sources and using arch AUR repository.

**Comment by BranDougherty** [comment]
I highly recommend trying the CMake build system, it will automatically check out the right release for you. These commands should get you there on Arch:
```bash
pacman -S base-devel cmake fpc protobuf openssl sdl2 openal physfs freetype2
mkdir build
cd build
cmake ..
make
```

That being said you can either download the release from the GNS releases page https://github.com/ValveSoftware/GameNetworkingSockets/releases
or clone it and `git checkout v1.3.0`. Then follow the GNS repo's instructions to build it manually.

**Comment by BranDougherty** [comment]
Going to assume this worked for you, feel free to open another issue.
