### ISSUE TITLE
Maps not loaded (Mac OSX)

### ISSUE THREAD

**Issue by themangokid** [opensoldat/opensoldat#8]
There is a problem when loading maps on the mac client. I suspect it is  either:

1. The map is not downloaded, in the correct folder
2. The map is not downloaded at all

![Error when map is not found](https://user-images.githubusercontent.com/1214022/82894151-69d62d00-9f52-11ea-9e23-77d61ceca145.png)
![Violation](https://user-images.githubusercontent.com/1214022/82894155-6c388700-9f52-11ea-80d1-23dbd5c77c49.png)

**Comment by furai** [comment]
Did you copy the base repo? You need shared folder and maps from it. And the error seems about incorrect permissions on your Soldat.app. Soldat can't write inside of it. Probably there's not even a maps folder inside the app.

**Comment by themangokid** [comment]
I have not compiled it myself. This is the version I got from helloer. There might be a difference in that version and the one I use.

**Comment by Shoozza** [comment]
Please retest with a build from this repository if possible.

**Comment by themangokid** [comment]
I'll not have time for this atm. Waiting for a newly compiled version because I have a different version.

**Comment by helloer** [comment]
This issue is about [1.7.1 macOS version,](https://wiki.soldat.pl/index.php/Soldat_on_macOS_and_Linux) which is unsupported and not relevant for 1.8.
