### ISSUE TITLE
Can you create a .zip with all the files included for launch?

### ISSUE THREAD

**Issue by Getta91** [opensoldat/opensoldat#9]
Is this possible?

**Comment by themangokid** [comment]
Guide: https://github.com/Soldat/soldat/wiki/A-beginner%27s-guide-to-Soldat-development
I'll ask on discord. We have a dedicated channel for development there. https://discord.gg/soldat

**Comment by Getta91** [comment]
thanks.

**Comment by Shoozza** [comment]
Nightly builds will come at some point. Currently you have to build it yourself.

**Comment by helloer** [comment]
~Nightly~ latest build for all platforms are available to download @ https://nightly.link/Soldat/soldat/workflows/soldat/develop or in `Actions` tab

**Comment by BranDougherty** [comment]
Soon we should be able to have a release with the [launcher](https://github.com/rzaba0/soldat-launcher) but IMO the current [continuous release](https://github.com/opensoldat/opensoldat/releases/tag/continuous) is good enough to call this closed.
